### PR TITLE
replace namedtuples with dicts and csv config file with json

### PR DESCRIPTION
**Pull request by karthik-shanmugam**
I added code to create dicts of namedtuples when getData() is called. I did not fully remove namedtuples from hibike; you can now pass a string argument to getData() to specify if the return type should be int, namedtuple, or dictionary, with the default being dictionary. namedtuples can now be easily removed entirely if needed. Even when the creation of namedtuple classes is removed, **hibike cannot be pickled due to the use of Queue objects**.

I also added a json config file, since our config data now involves nested lists. The old code for parsing csv files has not been removed; hibike now looks at the extension of the given config file to determine whether to parse it as a csv or json file. The default config file is now a json file.

### CODE REVIEW

**Comment by cduck** [comment]
This seems to help with the error I was seeing in runtime but I think runtime still doesn't know what to do with dictionaries either.  runtime.py doesn't crash but the Dawn UI is acting weird.

I found one bug in your above code: it doesn't return a dictionary if the device hasn't responded with a value for that param yet.  It's just returns an empty named tuple instead of a dictionary.  My fix for that is here: https://github.com/cduck/hibike/tree/namedTupleFix

**Comment by karthik-shanmugam** [comment]
I completely forgot I was initializing the data to an empty namedtuple. We
can use your fix, and also initialize with an empty tuple instead of a
namedtuple. Alternatively, the better fix would be to initialize with a
bytearray of 0's of the correct size.

**Comment by cduck** [comment]
The second solution sounds better.

Also, what happens if the sensor returns a packet with an incorrect
length?  Does it crash when unpacking it?

On Dec 29, 2015, at 4:59 PM, karthik-shanmugam notifications@github.com
wrote:

I completely forgot I was initializing the data to an empty namedtuple. We
can use your fix, and also initialize with an empty tuple instead of a
namedtuple. Alternatively, the better fix would be to initialize with a
bytearray of 0's of the correct size.

**Comment by akumaraguru** [comment]
How important is it that Hibike is picklable? Not using Queue objects seems really painful and hazardous at this stage.

Also, karthik, what is the purpose of the Description Request/Response packets? If it's just for debugging purposes, that's fine, but we shouldn't be sending over that kind of information to begin with. All the information in the DESCRIPTION string is stuff that should be pulled from the config file, not from the device itself.

**Comment by karthik-shanmugam** [comment]
@AravindK95 : It's only used when the BBB can't find the device info in it's
config file. The BBB adds the info to its config file after requesting it
from the device so it won't request it ever again. This way the config
files can update themselves if we release a new device.

@cduck: Hibike crashes if the DataUpdate is the wrong size; this is
something I should fix.

**Comment by karthik-shanmugam** [comment]
@cduck Actually I'm not sure how to handle this. I can raise an exception, return garbage, print a warning and return garbage, return an empty dict, etc. What do you think would be the best way to handle this? The values are only unpacked when a call to getData is made (the thread itself never unpacks) so raising an exception might be ok (which is what will occur right now)

**Comment by akumaraguru** [comment]
@karthik Just my two cents, but it definitely shouldn't crash/raise an unhandled exception. We can't risk having the entire system fail if only one buggy device is connected. The safest option is to return a dict with all the expected keys, but None or 0 as the values, so that nothing further up the stack in runtime has to worry about KeyErrors. Adding a print statement will be helpful for debugging.

**Pull request closed without merging**
